In [27]:
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt

### Data description
The dataset is composed by a set of 1500 matrices (1002 x 1002 elements) of {0,1}. Each matrix represent a random realization of a 2-d porous media made by packing *impenetrable disks*.

Each element of the matrix represent the value of an indicator function $$ I^{i}(x) = \left\{
    \begin{array}\\
        1 & \mbox{if } \ x \in V_{solid} \\
        0 & \mbox{if } \ x \in V_{void} \\
    \end{array}
\right.$$


The porosity $ \phi_i$ is calculated by the 1-point probability $ S_1(x) = \big \langle I^{i}(x) \big \rangle $, which is the ensable mean over all matrices.

### Example

In [3]:
ex = np.load('exp_1316_Mat_G.npy')
print(ex)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 ...
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
phi_ex = np.mean(ex)
print('phi_i =','{:.3f}'.format(phi_ex))

phi_i = 0.661


### Analysis

In [17]:
dir_list = os.listdir()
files = [elem for elem in dir_list if 'exp' in elem]

In [19]:
m_means = []
for file in files:
    m = np.load(file)
    m_means.append(np.mean(m))

In [23]:
phi_ens = np.mean(m_means)
phi_std_dev = np.std(m_means)

In [25]:
print('phi_ensable =','{:.3f}'.format(phi_ens))
print('the standard deviation is =','{:.3f}'.format(phi_std_dev))

phi_ensable = 0.663
the standard deviation is = 0.023
